#!/usr/bin/env python3

from collections import namedtuple
from urllib import request

bonnie_version = "0.3.2"
nvm_version = "0.39.1"
rustup_target = "wasm32-unknown-unknown"

PerseusRelease = namedtuple(
    "PerseusRelease",
    [
        "tag",
        "os"
    ]
)

OperatingSystem = namedtuple(
    "OperatingSystem",
    [
        "name",
        "version",
        "dep"
    ]
)

OSTarget = namedtuple(
    "OSTarget",
    [
        "bash",
        "pkg",
        "rust"
    ]
)

Dependency = namedtuple(
    "Dependency",
    [
        "name",
        "version"
    ]
)

perseus_deps = [
    PerseusRelease(
        "0.3.0",
        OperatingSystem(
            "alpine",
            "3.15.6",
            [
                Dependency("alpine-sdk",        "1.0-r1"),
                Dependency("binaryen",          "104"),
                Dependency("browser-sync",      "2.27.7"),
                Dependency("concurrently",      "6.5.1"),
                Dependency("esbuild",           "0.14.6"),
                Dependency("git",               "2.34.1"),
                Dependency("linux-headers",     "5.10.41-r0"),
                Dependency("make",              "4.3-r0"),
                Dependency("musl-dev",          "1.2.2-r7"),
                Dependency("node",              "17.3.0"),
                Dependency("npm",               "8.3.0"),
                Dependency("openrc",            "0.44.7-r5"),
                Dependency("openssl",           "1.1.1q"),
                Dependency("perl",              "5.34.0-r1"),
                Dependency("perseus-size-opt",  "0.1.7"),
                Dependency("pkgconf",           "1.8.0-r0"),
                Dependency("rust",              "1.57.0"),
                Dependency("rustup",            "1.24.3"),
                Dependency("serve",             "13.0.2"),
                Dependency("tailwindcss",       "3.0.7"),
                Dependency("wasm-pack",         "0.10.2"),
                Dependency("zlib-dev",          "1.2.12-r3"),
            ],
        ),
    ),
    PerseusRelease(
        "0.3.1",
        OperatingSystem(
            "alpine",
            "3.15.6",
            [
                Dependency("alpine-sdk",        "1.0-r1"),
                Dependency("binaryen",          "104"),
                Dependency("browser-sync",      "2.27.7"),
                Dependency("concurrently",      "7.0.0"),
                Dependency("esbuild",           "0.14.10"),
                Dependency("git",               "2.34.1"),
                Dependency("linux-headers",     "5.10.41-r0"),
                Dependency("make",              "4.3-r0"),
                Dependency("musl-dev",          "1.2.2-r7"),
                Dependency("node",              "17.3.0"),
                Dependency("npm",               "8.3.0"),
                Dependency("openrc",            "0.44.7-r5"),
                Dependency("openssl",           "1.1.1q"),
                Dependency("perl",              "5.34.0-r1"),
                Dependency("perseus-size-opt",  "0.1.7"),
                Dependency("pkgconf",           "1.8.0-r0"),
                Dependency("rust",              "1.57.0"),
                Dependency("rustup",            "1.24.3"),
                Dependency("serve",             "13.0.2"),
                Dependency("tailwindcss",       "3.0.8"),
                Dependency("wasm-pack",         "0.10.2"),
                Dependency("zlib-dev",          "1.2.12-r3"),
            ],
        ),
    ),
    PerseusRelease(
        "0.3.2",
        OperatingSystem(
            "alpine",
            "3.15.6",
            [
                Dependency("alpine-sdk",        "1.0-r1"),
                Dependency("binaryen",          "104"),
                Dependency("browser-sync",      "2.27.7"),
                Dependency("concurrently",      "7.0.0"),
                Dependency("esbuild",           "0.14.11"),
                Dependency("git",               "2.34.1"),
                Dependency("linux-headers",     "5.10.41-r0"),
                Dependency("make",              "4.3-r0"),
                Dependency("musl-dev",          "1.2.2-r7"),
                Dependency("node",              "17.3.1"),
                Dependency("npm",               "8.3.0"),
                Dependency("openrc",            "0.44.7-r5"),
                Dependency("openssl",           "1.1.1q"),
                Dependency("perl",              "5.34.0-r1"),
                Dependency("perseus-size-opt",  "0.1.7"),
                Dependency("pkgconf",           "1.8.0-r0"),
                Dependency("rust",              "1.57.0"),
                Dependency("rustup",            "1.24.3"),
                Dependency("serve",             "13.0.2"),
                Dependency("tailwindcss",       "3.0.12"),
                Dependency("wasm-pack",         "0.10.2"),
                Dependency("zlib-dev",          "1.2.12-r3"),
            ],
        ),
    ),
    PerseusRelease(
        "0.3.3",
        OperatingSystem(
            "alpine",
            "3.15.6",
            [
                Dependency("alpine-sdk",        "1.0-r1"),
                Dependency("binaryen",          "105"),
                Dependency("browser-sync",      "2.27.7"),
                Dependency("concurrently",      "7.0.0"),
                Dependency("esbuild",           "0.14.21"),
                Dependency("git",               "2.35.1"),
                Dependency("linux-headers",     "5.10.41-r0"),
                Dependency("make",              "4.3-r0"),
                Dependency("musl-dev",          "1.2.2-r7"),
                Dependency("node",              "17.5.0"),
                Dependency("npm",               "8.4.1"),
                Dependency("openrc",            "0.44.7-r5"),
                Dependency("openssl",           "1.1.1q"),
                Dependency("perl",              "5.34.0-r1"),
                Dependency("perseus-size-opt",  "0.1.7"),
                Dependency("pkgconf",           "1.8.0-r0"),
                Dependency("rust",              "1.58.1"),
                Dependency("rustup",            "1.24.3"),
                Dependency("serve",             "13.0.2"),
                Dependency("tailwindcss",       "3.0.22"),
                Dependency("wasm-pack",         "0.10.2"),
                Dependency("zlib-dev",          "1.2.12-r3"),
            ],
        ),
    ),
    PerseusRelease(
        "0.3.4",
        OperatingSystem(
            "alpine",
            "3.15.6",
            [
                Dependency("alpine-sdk",        "1.0-r1"),
                Dependency("binaryen",          "105"),
                Dependency("browser-sync",      "2.27.9"),
                Dependency("concurrently",      "7.1.0"),
                Dependency("esbuild",           "0.14.36"),
                Dependency("git",               "2.36.0"),
                Dependency("linux-headers",     "5.10.41-r0"),
                Dependency("make",              "4.3-r0"),
                Dependency("musl-dev",          "1.2.2-r7"),
                Dependency("node",              "18.0.0"),
                Dependency("npm",               "8.6.0"),
                Dependency("openrc",            "0.44.7-r5"),
                Dependency("openssl",           "1.1.1q"),
                Dependency("perl",              "5.34.0-r1"),
                Dependency("perseus-size-opt",  "0.1.8"),
                Dependency("pkgconf",           "1.8.0-r0"),
                Dependency("rust",              "1.60.0"),
                Dependency("rustup",            "1.24.3"),
                Dependency("serve",             "13.0.2"),
                Dependency("tailwindcss",       "3.0.24"),
                Dependency("wasm-pack",         "0.10.2"),
                Dependency("zlib-dev",          "1.2.12-r3"),
            ],
        ),
    ),
    PerseusRelease(
        "0.3.5",
        OperatingSystem(
            "alpine",
            "3.15.6",
            [
                Dependency("alpine-sdk",        "1.0-r1"),
                Dependency("binaryen",          "105"),
                Dependency("browser-sync",      "2.27.10"),
                Dependency("concurrently",      "7.1.0"),
                Dependency("esbuild",           "0.14.36"),
                Dependency("git",               "2.36.0"),
                Dependency("linux-headers",     "5.10.41-r0"),
                Dependency("make",              "4.3-r0"),
                Dependency("musl-dev",          "1.2.2-r7"),
                Dependency("node",              "18.0.0"),
                Dependency("npm",               "8.6.0"),
                Dependency("openrc",            "0.44.7-r5"),
                Dependency("openssl",           "1.1.1q"),
                Dependency("perl",              "5.34.0-r1"),
                Dependency("perseus-size-opt",  "0.1.9"),
                Dependency("pkgconf",           "1.8.0-r0"),
                Dependency("rust",              "1.60.0"),
                Dependency("rustup",            "1.24.3"),
                Dependency("serve",             "13.0.2"),
                Dependency("tailwindcss",       "3.0.24"),
                Dependency("wasm-pack",         "0.10.2"),
                Dependency("zlib-dev",          "1.2.12-r3"),
            ],
        ),
    ),
    PerseusRelease(
        "0.4.0-beta.1",
        OperatingSystem(
            "alpine",
            "3.16.2",
            [
                Dependency("alpine-sdk",        "1.0-r1"),
                Dependency("binaryen",          "108"),
                Dependency("browser-sync",      "2.27.10"),
                Dependency("concurrently",      "7.2.1"),
                Dependency("esbuild",           "0.14.42"),
                Dependency("git",               "2.36.1"),
                Dependency("linux-headers",     "5.16.7-r1"),
                Dependency("make",              "4.3-r0"),
                Dependency("musl-dev",          "1.2.3-r0"),
                Dependency("node",              "18.2.0"),
                Dependency("npm",               "8.9.0"),
                Dependency("openrc",            "0.44.10-r7"),
                Dependency("openssl",           "1.1.1q"),
                Dependency("perl",              "5.34.1-r0"),
                Dependency("perseus-size-opt",  "0.1.7"),
                Dependency("pkgconf",           "1.8.0-r1"),
                Dependency("rust",              "1.61.0"),
                Dependency("rustup",            "1.24.3"),
                Dependency("serve",             "13.0.2"),
                Dependency("tailwindcss",       "3.0.24"),
                Dependency("wasm-pack",         "0.10.2"),
                Dependency("zlib-dev",          "1.2.12-r3"),
            ],
        ),
    ),
    PerseusRelease(
        "0.4.0-beta.2",
        OperatingSystem(
            "alpine",
            "3.16.2",
            [
                Dependency("alpine-sdk",        "1.0-r1"),
                Dependency("binaryen",          "109"),
                Dependency("browser-sync",      "2.27.10"),
                Dependency("concurrently",      "7.2.2"),
                Dependency("esbuild",           "0.14.47"),
                Dependency("git",               "2.36.2"),
                Dependency("linux-headers",     "5.16.7-r1"),
                Dependency("make",              "4.3-r0"),
                Dependency("musl-dev",          "1.2.3-r0"),
                Dependency("node",              "18.4.0"),
                Dependency("npm",               "8.12.1"),
                Dependency("openrc",            "0.44.10-r7"),
                Dependency("openssl",           "1.1.1q"),
                Dependency("perl",              "5.34.1-r0"),
                Dependency("perseus-size-opt",  "0.1.7"),
                Dependency("pkgconf",           "1.8.0-r1"),
                Dependency("rust",              "1.61.0"),
                Dependency("rustup",            "1.24.3"),
                Dependency("serve",             "13.0.3"),
                Dependency("tailwindcss",       "3.1.4"),
                Dependency("wasm-pack",         "0.10.2"),
                Dependency("zlib-dev",          "1.2.12-r3"),
            ],
        ),
    ),
    PerseusRelease(
        "0.4.0-beta.3",
        OperatingSystem(
            "alpine",
            "3.16.2",
            [
                Dependency("alpine-sdk",        "1.0-r1"),
                Dependency("binaryen",          "109"),
                Dependency("browser-sync",      "2.27.10"),
                Dependency("concurrently",      "7.3.0"),
                Dependency("esbuild",           "0.14.48"),
                Dependency("git",               "2.37.1"),
                Dependency("linux-headers",     "5.16.7-r1"),
                Dependency("make",              "4.3-r0"),
                Dependency("musl-dev",          "1.2.3-r0"),
                Dependency("node",              "18.4.0"),
                Dependency("npm",               "8.12.1"),
                Dependency("openrc",            "0.44.10-r7"),
                Dependency("openssl",           "1.1.1q"),
                Dependency("perl",              "5.34.1-r0"),
                Dependency("perseus-size-opt",  "0.1.7"),
                Dependency("pkgconf",           "1.8.0-r1"),
                Dependency("rust",              "1.62.0"),
                Dependency("rustup",            "1.24.3"),
                Dependency("serve",             "13.0.2"),
                Dependency("tailwindcss",       "3.1.4"),
                Dependency("wasm-pack",         "0.10.3"),
                Dependency("zlib-dev",          "1.2.12-r3"),
            ],
        ),
    ),
    PerseusRelease(
        "0.4.0-beta.4",
        OperatingSystem(
            "alpine",
            "3.16.2",
            [
                Dependency("alpine-sdk",        "1.0-r1"),
                Dependency("binaryen",          "109"),
                Dependency("browser-sync",      "2.27.10"),
                Dependency("concurrently",      "7.3.0"),
                Dependency("esbuild",           "0.14.49"),
                Dependency("git",               "2.37.1"),
                Dependency("linux-headers",     "5.16.7-r1"),
                Dependency("make",              "4.3-r0"),
                Dependency("musl-dev",          "1.2.3-r0"),
                Dependency("node",              "18.6.0"),
                Dependency("npm",               "8.13.2"),
                Dependency("openrc",            "0.44.10-r7"),
                Dependency("openssl",           "1.1.1q"),
                Dependency("perl",              "5.34.1-r0"),
                Dependency("perseus-size-opt",  "0.1.7"),
                Dependency("pkgconf",           "1.8.0-r1"),
                Dependency("rust",              "1.62.0"),
                Dependency("rustup",            "1.24.3"),
                Dependency("serve",             "13.0.2"),
                Dependency("tailwindcss",       "3.1.6"),
                Dependency("wasm-pack",         "0.10.3"),
                Dependency("zlib-dev",          "1.2.12-r3"),
            ],
        ),
    ),
    PerseusRelease(
        "0.4.0-beta.5",
        OperatingSystem(
            "alpine",
            "3.16.2",
            [
                Dependency("alpine-sdk",        "1.0-r1"),
                Dependency("binaryen",          "109"),
                Dependency("browser-sync",      "2.27.10"),
                Dependency("concurrently",      "7.3.0"),
                Dependency("esbuild",           "0.14.49"),
                Dependency("git",               "2.37.1"),
                Dependency("linux-headers",     "5.16.7-r1"),
                Dependency("make",              "4.3-r0"),
                Dependency("musl-dev",          "1.2.3-r0"),
                Dependency("node",              "18.6.0"),
                Dependency("npm",               "8.13.2"),
                Dependency("openrc",            "0.44.10-r7"),
                Dependency("openssl",           "1.1.1q"),
                Dependency("perl",              "5.34.1-r0"),
                Dependency("perseus-size-opt",  "0.1.7"),
                Dependency("pkgconf",           "1.8.0-r1"),
                Dependency("rust",              "1.62.0"),
                Dependency("rustup",            "1.25.1"),
                Dependency("serve",             "13.0.4"),
                Dependency("tailwindcss",       "3.1.6"),
                Dependency("wasm-pack",         "0.10.3"),
                Dependency("zlib-dev",          "1.2.12-r3"),
            ],
        ),
    ),
    PerseusRelease(
        "0.4.0-beta.6",
        OperatingSystem(
            "alpine",
            "3.16.2",
            [
                Dependency("alpine-sdk",        "1.0-r1"),
                Dependency("binaryen",          "109"),
                Dependency("browser-sync",      "2.27.10"),
                Dependency("concurrently",      "7.3.0"),
                Dependency("esbuild",           "0.15.3"),
                Dependency("git",               "2.37.2"),
                Dependency("linux-headers",     "5.16.7-r1"),
                Dependency("make",              "4.3-r0"),
                Dependency("musl-dev",          "1.2.3-r0"),
                Dependency("node",              "18.7.0"),
                Dependency("npm",               "8.15.0"),
                Dependency("openrc",            "0.44.10-r7"),
                Dependency("openssl",           "1.1.1q"),
                Dependency("perl",              "5.34.1-r0"),
                Dependency("perseus-size-opt",  "0.1.7"),
                Dependency("pkgconf",           "1.8.0-r1"),
                Dependency("rust",              "1.63.0"),
                Dependency("rustup",            "1.25.1"),
                Dependency("serve",             "14.0.1"),
                Dependency("tailwindcss",       "3.1.8"),
                Dependency("wasm-pack",         "0.10.3"),
                Dependency("zlib-dev",          "1.2.12-r3"),
            ],
        ),
    ),
    PerseusRelease(
        "0.4.0-beta.7",
        OperatingSystem(
            "alpine",
            "3.16.2",
            [
                Dependency("alpine-sdk",        "1.0-r1"),
                Dependency("binaryen",          "109"),
                Dependency("browser-sync",      "2.27.10"),
                Dependency("concurrently",      "7.3.0"),
                Dependency("esbuild",           "0.15.3"),
                Dependency("git",               "2.37.2"),
                Dependency("linux-headers",     "5.16.7-r1"),
                Dependency("make",              "4.3-r0"),
                Dependency("musl-dev",          "1.2.3-r0"),
                Dependency("node",              "18.7.0"),
                Dependency("npm",               "8.15.0"),
                Dependency("openrc",            "0.44.10-r7"),
                Dependency("openssl",           "1.1.1q"),
                Dependency("perl",              "5.34.1-r0"),
                Dependency("perseus-size-opt",  "0.1.7"),
                Dependency("pkgconf",           "1.8.0-r1"),
                Dependency("rust",              "1.63.0"),
                Dependency("rustup",            "1.25.1"),
                Dependency("serve",             "14.0.1"),
                Dependency("tailwindcss",       "3.1.8"),
                Dependency("wasm-pack",         "0.10.3"),
                Dependency("zlib-dev",          "1.2.12-r3"),
            ],
        ),
    ),
]